models.py
from utils.db import db
from sqlalchemy.dialects.postgresql import UUID
import datetime
import uuid

class Author(db.Model):
    __tablename__ = 'authors'
    id = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4())
    name = db.Column(db.String(100), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    created_at = db.Column(db.DateTime(timezone=True), default=datetime.datetime.now())
    books = db.relationship("Book", backref="author")

    def to_dict(self):
        return {
            "id": str(self.id),
            "name": self.name,
            "age": self.age,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%M:%S"),
            "books": [book.to_dict() for book in self.books]
        }
    # def __repr__(self):
    #     return f"Author(id={str(self.id)!r}, name={self.name!r}, age={self.age!r}, created_at={self.created_at!r})"
    
class Book (db.Model):
    __tablename__ = 'books'
    id = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4())
    isbn = db.Column(db.String(255), nullable=False)
    name = db.Column(db.String(255), nullable=False)
    quantity_pages = db.Column(db.Integer, nullable=False, default=0)
    created_at = db.Column(db.DateTime, default=datetime.datetime.now())
    author_id = db.Column(UUID(as_uuid=True), db.ForeignKey('authors.id'))

app.py
from flask import Flask
from utils.db import db
from flask_migrate import Migrate
from config import config

def create_app():
    app = Flask(__name__)
    app.config.from_object(config['default'])
    db.init_app(app)

    Migrate(app, db)

    with app.app_context():
        db.create_all()

    from routes.hello_route import hello_route
    from routes.author_route import author_routes
    from routes.book_route import book_routes

    app.register_blueprint(hello_route)
    app.register_blueprint(author_routes)
    app.register_blueprint(book_routes)

    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True, host='0.0.0.0')

routes/author_route.py
from flask import Blueprint, jsonify, url_for, redirect, request, render_template, flash
import uuid, datetime
from models import Author
from utils.db import db
author_routes = Blueprint('author_routes', __name__)

def generate_uuid():
    return str(uuid.uuid4())

@author_routes.route('/authors/greeting', methods=['GET'])
def greeting():
    return jsonify({'message': 'Hello World!'}), 200

@author_routes.route('/authors', methods=['GET'])
def get_all():
    authors = Author.query.all()
    return render_template('authors/index.html', authors=authors)
    # try:
    #     authors = Author.query.all()
    #     authors_dict = [author.to_dict() for author in authors]
    #     return jsonify(authors_dict), 200
    # except Exception as e:
    #     return jsonify({'message': str(e)}), 500

@author_routes.route('/authors/create', methods=['GET'])
def create():
    return render_template('authors/create.html', author=None)

@author_routes.route('/authors', methods=['POST'])
def store():
    if request.method == 'POST':
        try:
            author = Author(
                id=generate_uuid(),
                name=request.form['name'],
                age=request.form['age'],
                created_at=datetime.datetime.now()
            )
            db.session.add(author)
            db.session.commit()
            flash('Author updated successfully', 'success')
            return redirect(url_for('author_routes.create', author=None))
        except Exception as e:
            return jsonify({'message': str(e)}), 500

@author_routes.route('/authors/<author_id>', methods=['GET'])
def show(author_id):
    author = Author.query.get(author_id)
    return render_template('authors/edit.html', author=author)
    # return jsonify(author.to_dict())

@author_routes.route('/authors/<author_id>/edit', methods=['GET'])
def edit(author_id):
    author = Author.query.get(author_id)
    return render_template('authors/edit.html', author=author)
    # return jsonify(author.to_dict())

@author_routes.route('/authors/<author_id>', methods=['POST'])
def update(author_id):
    if request.method == 'POST':
        try:
            author = Author.query.get(author_id)
            author.name = request.form['name']
            author.age = request.form['age']
            db.session.commit()
            flash('Author updated successfully', 'success')
            return redirect(url_for('author_routes.edit', author_id=author_id))
        except Exception as e:
            return jsonify({'message': str(e)}), 500

routes/book_route.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify, flash
import uuid
import datetime
from utils.db import db
from models import Book, Author

book_routes = Blueprint('book_routes', __name__)

def generate_uuid():
    return str(uuid.uuid4())

@book_routes.route('/books', methods=['GET'])
def get_all():
    books = Book.query.all()
    return render_template('books/index.html', books=books)

@book_routes.route('/books/create', methods=['GET'])
def create():
    authors = Author.query.all()
    return render_template('books/create.html', book=None, authors=authors)

@book_routes.route('/books', methods=['POST'])
def store():
    if request.method == 'POST':
        try:
            book = Book(
                id=generate_uuid(),
                isbn=request.form['isbn'],
                name=request.form['name'],
                author_id=request.form['author_id'],
                quantity_pages=int(request.form['quantity_pages']),
                created_at=datetime.datetime.now()
            )
            db.session.add(book)
            db.session.commit()
            flash('Book saved successfully', 'success')
            return redirect(url_for('book_routes.create', book=None))
        except Exception as e:
            return jsonify({'message': str(e)}), 500
    
    render_template('books/create.html', book=None)

@book_routes.route('/books/<author_id>', methods=['GET'])
def show(author_id):
    author = Book.query.get(author_id)
    return render_template('books/edit.html', author=author)
    # return jsonify(author.to_dict())

@book_routes.route('/books/<book_id>/edit', methods=['GET'])
def edit(book_id):
    authors = Author.query.all()
    book = Book.query.get(book_id)
    return render_template('books/edit.html', book=book, authors=authors)

@book_routes.route('/books/<book_id>', methods=['POST'])
def update(book_id):
    if request.method == 'POST':
        try:
            book = Book.query.get(book_id)
            book.isbn=request.form['isbn']
            book.name=request.form['name']
            book.author_id=request.form['author_id']
            book.quantity_pages=int(request.form['quantity_pages'])
            db.session.commit()
            flash('Book updated successfully', 'success')
            return redirect(url_for('book_routes.edit', book_id=book_id))
        except Exception as e:
            return jsonify({'message': str(e)}), 500

routes/hello_route.py
from flask import Blueprint

hello_route = Blueprint('hello_route', __name__)

@hello_route.route('/', methods=['GET'])
def index():
    return 'Welcome to Flask Application!'

templates/authors/create.html
{% extends 'layout/app.html' %}
{% block title %}New Author - {{ author.name }}{% endblock %}
{% block content %}
<div class="container">
    <h1>Author: {{ author.name }}</h1>
    <form action="{{ url_for('author_routes.store', author=None) }}" method="POST">
        <div class="input-group mb-3">
            <input type="text" name="name" value="" class="form-control" placeholder="Name"
                aria-label="name">
            <span class="input-group-text">.</span>
            <input type="number" name="age" value="" class="form-control" placeholder="Age"
                aria-label="Age">
        </div>

        <div class="input-group">
            <input type="submit" class="btn btn-outline-primary form-control" value="Save">
        </div>
    </form>
</div>
{% endblock %}

templates/authors/edit.html
{% extends 'layout/app.html' %}
{% block title %}Edit Author - {{ author.name }}{% endblock %}
{% block content %}
<div class="container">
    <h1>Author: {{ author.name }}</h1>
    <form action="{{ url_for('author_routes.update', author_id=author.id) }}" method="POST">
        <div class="input-group mb-3">
            <input type="text" name="name" value="{{author.name}}" class="form-control" placeholder="Name"
                aria-label="name">
            <span class="input-group-text">.</span>
            <input type="number" name="age" value="{{author.age}}" class="form-control" placeholder="Age"
                aria-label="Age">
        </div>

        <div class="input-group">
            <input type="submit" class="btn btn-outline-success form-control" value="Save changes">
        </div>
    </form>
</div>
{% endblock %}

templates/authors/index.html
{% extends 'layout/app.html' %}
{% block title %}Authors - Flask App{% endblock %}
{% block content %}
<div class="container mt-3">
    <h1>Authors</h1>
    <div class="text-end">
        <a href="/authors/create" class="btn btn-sm btn-outline-success">New Author</a>
    </div>
    <table class="table table-responsive table-sm" id="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Age</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for author in authors %}
            <tr>
                <td>{{ loop.index}}.</td>
                <td>{{ author.name }}</td>
                <td>{{ author.age }}</td>
                <td>{{ author.created_at }}</td>
                <td><a href="/authors/{{ author.id }}/edit" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil-square"></i> Edit</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table').DataTable();
    })
</script>
{% endblock %}

templates/books/create.html
{% extends 'layout/app.html' %}
{% block title %}New Book{% endblock %}
{% block content %}
<div class="container">
    <h1>New book</h1>
    <form action="{{ url_for('book_routes.store', book=None) }}" method="POST">
        <div class="input-group mb-3">
            <span class="input-group-text">#</span>
            <select name="author_id" class="form-control" aria-label="author_id" required>
                <option selected disabled>Author</option>
                {% for author in authors %}
                <option value="{{ author.id }}">{{ author.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">.</span>
            <input type="text" name="isbn" value="" class="form-control" pattern="[0-9]{3}-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,7}-[0-9]{1}" title="Ingrese un ISBN válido (formato: 123-4-56789-012-3)" placeholder="####" aria-label="isbn">
            <span class="input-group-text">.</span>
            <input type="text" name="name" value="" class="form-control" placeholder="Book Name" aria-label="name" required>
            <span class="input-group-text">#</span>
            <input type="number" name="quantity_pages" value="" min="1" class="form-control" placeholder="Pages" aria-label="quantity_pages" required>
        </div>
        <div class="input-group">
            <input type="submit" class="btn btn-outline-primary form-control" value="Save">
        </div>
    </form>
</div>
{% endblock %}

templates/books/edit.html
{% extends 'layout/app.html' %}
{% block title %}Edit Book - {{ book.name }}{% endblock %}
{% block content %}
<div class="container">
    <h1>Book: {{ book.name }}</h1>
    <form action="{{ url_for('book_routes.update', book_id=book.id) }}" method="POST">
        <div class="input-group mb-3">
            <span class="input-group-text">#</span>
            <select name="author_id" class="form-control" id="form_author_id" aria-label="author_id" required>
                <option selected disabled>Author</option>
                {% for author in authors %}
                <option value="{{ author.id }}">{{ author.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">.</span>
            <input type="text" name="isbn" value="{{book.isbn}}" class="form-control" pattern="[0-9]{3}-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,7}-[0-9]{1}" title="Ingrese un ISBN válido (formato: 123-4-56789-012-3)" placeholder="####" aria-label="isbn">
            <span class="input-group-text">.</span>
            <input type="text" name="name" value="{{book.name}}" class="form-control" placeholder="Book Name" aria-label="name" required>
            <span class="input-group-text">#</span>
            <input type="number" name="quantity_pages" value="{{book.quantity_pages}}" min="1" class="form-control" placeholder="Pages" aria-label="quantity_pages" required>
        </div>

        <div class="input-group">
            <input type="submit" class="btn btn-outline-success form-control" value="Save changes">
        </div>
    </form>
</div>
{% endblock %}
{% block scripts %}
<script>
    document.querySelector('#form_author_id').value = "{{book.author_id}}";
</script>
{% endblock %}

templates/books/index.html
{% extends 'layout/app.html' %}
{% block title %}Books - Flask App{% endblock %}
{% block content %}
<div class="container mt-3">
    <h1>Books</h1>
    <div class="text-end">
        <a href="/books/create" class="btn btn-sm btn-outline-success">New Book</a>
    </div>
    <table class="table table-responsive table-sm" id="table">
        <thead>
            <tr>
                <th>Isbn</th>
                <th>Author</th>
                <th>Name</th>
                <th>Pages</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{ book.isbn }}</td>
                <td>{{ book.author.name }}</td>
                <td>{{ book.name }}</td>
                <td>{{ book.quantity_pages }}</td>
                <td>{{ book.created_at }}</td>
                <td><a href="/books/{{ book.id }}/edit" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil-square"></i> Edit</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table').DataTable();
    })
</script>
{% endblock %}

templates/layout/app.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Books - Flask App{% endblock %}</title>
    <link rel="shortcut icon" href="/static/icons/icons.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css" rel="stylesheet">
    {% block styles %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/authors">Authors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/books">Books</a>
                    </li>
                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                    </li> -->
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% block content %}Body{% endblock %}
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.min.js"></script>
    {% block scripts %}{% endblock %}
</body>

</html>